GET https://cse-341-project1-b4e1.onrender.com/users

###
GET http://localhost:3000

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/67db1784bbcee039ccd2fc8b

### create new user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email": "nikki@test.mail",
    "username": "nikki",
    "name": "Tita Nikki",
    "ipaddress": "192.0.168.0000"
}

### update user
PUT http://localhost:3000/users/67db1784bbcee039ccd2fc8b HTTP/1.1
Content-Type: application/json

{
    "email": "newkirokiropi.com",
    "username": "newkirokiropi",
    "name": "New Kirokiropi",
    "ipaddress": "192.168.009.229"
}

### delete user
DELETE http://localhost:3000/users/67db27a346c56fe064440234 HTTP/1.1